artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Akash-0818/TestRepo/raw/refs/heads/master/Dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  
data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Dataset
  status_file: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/Dataset
  train_data_path: artifacts/data_transformation/train_data.npy
  train_labels_path: artifacts/data_transformation/train_labels.npy
  test_data_path: artifacts/data_transformation/test_data.npy 
  test_labels_path: artifacts/data_transformation/test_labels.npy

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train_data.npy
  train_labels_path: artifacts/data_transformation/train_labels.npy
  test_data_path: artifacts/data_transformation/test_data.npy 
  test_labels_path: artifacts/data_transformation/test_labels.npy
  model_name: model.joblib
